services:
  api:
    image: ghcr.io/jamersom/market-data-api:${IMAGE_TAG:-dev}

    environment:
      APP_ENV: ${APP_ENV:-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FORMAT: ${LOG_FORMAT:-json}

      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@b3-data-hub_postgres:5432/${POSTGRES_DB}?sslmode=disable

      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS:-10}
      DB_MIN_CONNECTIONS: ${DB_MIN_CONNECTIONS:-2}
      DB_MAX_CONN_LIFETIME: ${DB_MAX_CONN_LIFETIME:-30m}
      DB_CONNECT_TIMEOUT: ${DB_CONNECT_TIMEOUT:-5s}

    networks:
      - b3_data_hub
      - DockerNet

    deploy:
      replicas: ${API_REPLICAS:-1}

      restart_policy:
        condition: on-failure

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.marketdata.rule=Host(marketdata.techcomp.net.br)"
        - "traefik.http.routers.marketdata.entrypoints=websecure"
        - "traefik.http.routers.marketdata.tls=true"
        - "traefik.http.routers.marketdata.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.marketdata.loadbalancer.server.port=8080"
        - "traefik.docker.network=DockerNet"


networks:
  b3_data_hub:
    external: true
    name: b3-data-hub_b3_data_hub

  DockerNet:
    external: true
    name: DockerNet